apiVersion: v1
appVersion: "1.0"
description: A Helm chart for Kubernetes
home: https://github.com/ManagedKube/helm-charts
icon: https://github.com/ManagedKube/helm-charts
maintainers:
- email: info@managedkube.com
  name: Garland
name: standard-application
version: 1.0.11
